// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfzcpkzfxhvmlrczswum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmemNwa3pmeGh2bWxyY3pzd3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDcyODksImV4cCI6MjA3MjcyMzI4OX0.X8gbHDLgt_Ba89I2H-ysrmGvqieMXLydTYBG9RPMd4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});